Fix TestColumnarPageProcessor
When TestColumnarPageProcessor test methods run concurrently it's
possible to see test failures due to the exception below as multiple
threads will be sharing the PageProcessor instance (hence the
ExpressionProfiler instance). This change fixes that by creating a new
PageProcessor for each test method.

com.google.common.base.VerifyException: start() is not called
	at com.google.common.base.Verify.verify(Verify.java:123)
	at com.facebook.presto.sql.gen.ExpressionProfiler.stop(ExpressionProfiler.java:59)